version: "3"
services:
  nginx:
    build: nginx
    image: nginx_img
    container_name: "nginx"
    restart: unless-stopped
    # Dont start nginx server until flask-api up
    depends_on:
      - backend
    tty: true
    ports:
      - '80:80'

  frontend:
    build:
      context: ./frontend
    container_name: "frontend"
    volumes:
      - shared:/app/dist/
      - ~/docker_app/logs/api:/app/logs
    ports:
      - '8081:8081'
  backend:
    build:
      context: ./backend
    container_name: "backend"
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: db
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: 1234567
      MONGODB_HOSTNAME: db
    ports:
      - "5000:80"
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo
    container_name: "mongodb"
    volumes:
        - ./docker-entrypoint.sh:/entrypoint.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234567
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_COLLECTION: board
    ports:
      - "27017:27017"
    command: mongod --auth

volumes:
  shared: {}
